# Generated by Django 4.1.5 on 2023-02-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pic',
            field=models.ImageField(default='patient/default-user.png', upload_to='patient/'),
        ),
    ]
