# Generated by Django 4.1.5 on 2023-02-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_patient_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(default='1234', max_length=10),
        ),
    ]
