# Generated by Django 4.1.4 on 2023-01-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_booking_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presciption',
            name='intake_time',
        ),
        migrations.RemoveField(
            model_name='presciption',
            name='medicine_time',
        ),
        migrations.AddField(
            model_name='presciption',
            name='prescription_notes',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
